services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    depends_on:
      - redis
    ports:
      - "4200:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      REDIS_HOST: redis
      REDIS_PORT: 6379

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
