FROM oven/bun:1.2.18-alpine AS deps

WORKDIR /app

COPY package.json bun.lock ./
RUN bun install --frozen-lockfile

FROM node:24-alpine

WORKDIR /app

RUN apk add --no-cache netcat-openbsd

COPY --from=deps /app/node_modules ./node_modules

COPY . .

COPY docker-entrypoint.sh /docker-entrypoint.sh
RUN chmod +x /docker-entrypoint.sh

CMD ["sh", "-c", "until nc -z db 5432; do echo 'Waiting for DB...'; sleep 1; done; npm run docker:start:dev"]
