FROM node:24-alpine

WORKDIR /app

COPY package*.json ./

RUN apk add --no-cache netcat-openbsd

RUN npm config set registry https://registry.npmjs.org/
RUN npm install

COPY . .
COPY docker-entrypoint.sh /docker-entrypoint.sh
RUN chmod +x /docker-entrypoint.sh
RUN npm run prisma:generate
RUN npm run build

CMD ["sh", "-c", "until nc -z db 5432; do echo 'Waiting for DB...'; sleep 1; done; npm run docker:start"]
